export { useCoachStore } from './model/coach.store'
export { coachEngineManager } from '@/shared/lib/engine/coach/CoachEngineManager'
export { default as CoachSidebar } from './ui/CoachSidebar.vue'
export { default as CoachSettings } from './ui/CoachSettings.vue'
export { default as QualityIcon } from './ui/QualityIcon.vue'
